### ISSUE TITLE
Improve display for collections

### ISSUE THREAD

**Issue by skurfer** [mikker/YosemiteInterface-qsplugin#9]
Things look a little weird when you start using <kbd>,</kbd>. I’m pretty sure you can tweak the height of the collection tray in a `QSCollectingSearchObjectView`, but it may not be that simple.

<img width="714" src="https://cloud.githubusercontent.com/assets/154676/17297582/526020b4-57d4-11e6-8169-a8079c6e264b.png">

Side note: I didn’t realize you had done more work on these interfaces. They’re almost to the point where I would recommend listing them in the preferences from the official plug-in system (with your permission of course).

**Comment by skurfer** [comment]
Since there’s typically a lot of space to the left of the icon, maybe the other icons could be “collected” there. No idea how hard that would be, though.

**Comment by mikker** [comment]
Thanks @skurfer! Piling the icons in the right sounds like an ok idea. I'm not sure when I'll find the time to update these though.

I feel like QS could really need an interface overhaul. Development is quite tedious and cumbersome. But I'm sure that's just _one_ of the many overhauls QS could use `¯\_(ツ)_/¯`

**Comment by pjrobertson** [comment]
I've just pushed a commit to [my fork](github.com/pjrobertson/yosemiteInterface-qsplugin/) that fixes this:

![Screen Region 2022-06-19 at 17 49 44](https://user-images.githubusercontent.com/150431/174475342-35c3ac10-b332-4225-942a-45ce92de98cf.png)

**Comment by mikker** [comment]
@pjrobertson would you be willing to contribute those changes back in the forms of PRs? I don't feel like closing this when it's not been fixed here.

**Comment by pjrobertson** [comment]
I created a repo over on the Quicksilver organisation here: https://github.com/quicksilver/YosemiteInterface-qsplugin

I also merged the light/dark interfaces into one, and made it a user-setting:
![Screen Region 2022-07-13 at 15 16 53](https://user-images.githubusercontent.com/150431/178673980-0bdd36c7-8050-45d5-bc0b-297fa4c768aa.png)


Happy to submit a PR here, or keep the code over at https://github.com/quicksilver/YosemiteInterface-qsplugin and make you a repo admin. Whichever you prefer, but I would recommend obsoleting the 'Dark' mode interface - so that  two code bases don't need maintaining :)
